### ISSUE TITLE
Project, room gallery images

### ISSUE THREAD

**Issue by Jakestudiofriday** [markendley/hmm#15]
Can we force the dimensions on these images? otherwise, the site is going to end up being out of whack once she starts using it

**Comment by Jakestudiofriday** [comment]
http://marke2.sg-host.com/hemma/project/

**Comment by markendley** [comment]
Is this do with the problem we had last week?
#3 


> You need to upload images 1800 x 1410 pixels.
> OR I can turn retina support off

**Comment by markendley** [comment]
turned retina off.
:)
