### ISSUE TITLE
Hosting details

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#16]
Hey Mark - can we move emilys website onto crucial server? If so, what are the steps we need to take? 

The current website was created with WIIX, but the hosting for both the website and Leah's email address is with GoDaddy.

WIX logins;

Email : leah@hemmainteriors.com.au
Password : Billie51

Go Daddy Login : 

leahrispoli@icloud.com

Password 

Billie51Billie51

**Comment by markendley** [comment]
The nameservers are with Wix, and then Wix points the emails back to Godaddy.

So 
1. Just change the nameservers back to Godaddy
2. Get Godaddy to point the A-record to Crucial

**Comment by LaraStudioFriday** [comment]
Ok - so if the client is happy to move to crucial - are you able to action the steps above?

**Comment by markendley** [comment]
Yes, lemme know :)

**Comment by LaraStudioFriday** [comment]
Yes client is happy to move to crucial

**Comment by LaraStudioFriday** [comment]
Looks good on a phone - for a larger screen can we please bring the margins in a bit more. The text seems really widely spaced out. 

Also, on a phone, can we move the arrows down underneath the image? 

Also, check out the video on jakes phone - the numbers are being cut off? will email this to you

**Comment by markendley** [comment]
hey Lara,

I was about to upload the files to the live server, but I can't find an account for Hemma?
