### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#17]
This is what you will see on the projects page

![Screen Shot 2019-12-04 at 11 28 54 am (1)](https://user-images.githubusercontent.com/55725505/70398241-81396080-1a6d-11ea-8bbf-b10180f49498.jpg)

This is what you will see on a room page (no icon or logo at the top)

![2Screen Shot 2019-12-vxc04 at 11 28 54 am copy](https://user-images.githubusercontent.com/55725505/70398252-91514000-1a6d-11ea-9e90-51487ad0602e.jpeg)

**Comment by markendley** [comment]
Ready!

When you edit the Room post in the wp admin you'll see a new field called "Icon".

As you can see
http://marke2.sg-host.com/hemma/room/

The place holder that I used was just the black version of the Hemma logo. When you upload SVGs just make sure they're white.

**Comment by LaraStudioFriday** [comment]
Ok please remove the icons - and put the hemma logo back on the rooms pages
<img width="453" alt="Screen Shot 2019-12-17 at 11 04 22 am" src="https://user-images.githubusercontent.com/55725505/70953379-24692600-20bd-11ea-9b82-de6d5be9a480.png">

**Comment by markendley** [comment]
done
