### ISSUE TITLE
Images on a phone are being stretched 

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#18]
<img width="335" alt="Screen Shot 2019-12-12 at 12 15 54 pm" src="https://user-images.githubusercontent.com/55725505/70674340-cb267e80-1cd9-11ea-9413-ce12bd3a0362.png">

**Comment by markendley** [comment]
fixed

**Comment by markendley** [comment]
(had to change the style in order to remove the funny scaling/proportions)
