### ISSUE TITLE
Who/What is/Process pages

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#2]
Instead of text overlapping logo and cutting off, could we have it so that the text fades out, and it fades out before it hits the logo
<img width="919" alt="Screen Shot 2019-11-12 at 11 00 43 am" src="https://user-images.githubusercontent.com/55725505/68630548-cedcaf00-053b-11ea-8415-a874171a9dc5.png">

**Comment by markendley** [comment]
I'll have to write the script so it'll take each line and decrease it's opacity as it reaches the top. It'll get more complicated when I make it responsive.

$450 +GST

**Comment by Jakestudiofriday** [comment]
<img width="1425" alt="Screen Shot 2019-11-19 at 8 56 42 am" src="https://user-images.githubusercontent.com/57921772/69097375-8cbaec80-0aaa-11ea-9765-a1a075bceff0.png">
 
Can this white box be removed then to match Flake studio

**Comment by markendley** [comment]
done
