### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#20]
Mark what is a cheap easy fix for this - 

FROM CLIENT - I need somewhere to add text for each project with the Builder, Photographer etc details. Doesn’t need a project description but just these basic details. What are your suggestions for where we could place this?

**Comment by LaraStudioFriday** [comment]
Mark please proceed on your quote

could one of the images be a text box - to write details about the project?
One paragraph?
or more?
it's gonna get tricky on mobile
because the height of the container is dependent on the size of the images
ok 
if you can keep it one paragraph or less I can do it for $150 +GST

**Comment by markendley** [comment]
done

when you edit the homepage you'll see the field

Obviously the image will display when viewed in portait mode(ipad portrait, iphone portrait).

**Comment by markendley** [comment]
done, check this page
http://marke2.sg-host.com/hemma/project/too-cool-for-thirroul/

**Comment by LaraStudioFriday** [comment]
Looks good on a phone - for a larger screen can we please bring the margins in a bit more. The text seems really widely spaced out.

Also, on a phone, can we move the arrows down underneath the image?

Also, check out the video on jakes phone - the numbers are being cut off? will email this to you

**Comment by markendley** [comment]
fixed
