### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#21]
Mark what is a quick and cheap fix for this?

Client would like an opening animation - with her logo animating in some way and then fades out to the homepage. 

Nothing as fancy as Topology or as silly as needing to click the logo to go to the homepage. 

This is how the client expressed it - Animated start, with the Logo flashing in one letter at a time, overlaid on photos, then straight to the home page, no need to click.

**Comment by markendley** [comment]
make each letter in the HEMMA logo, fade in one at a time.
splash page like Topology
$80 +GST

**Comment by LaraStudioFriday** [comment]
please proceed

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Feedback from client - Can we make the logo a little larger and linger a little longer than it does… it seems to disappear very quickly.

**Comment by markendley** [comment]
done
