### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#22]
Like what you did for plump and spry website - for the hemma homepage - can we have the option of  images being selected for a phone (portrait) and images being selected for a bigger screen (landscape)

**Comment by markendley** [comment]
Just the homepage  $50

**Comment by LaraStudioFriday** [comment]
Please proceed

**Comment by markendley** [comment]
done

**Comment by markendley** [comment]
done

when you edit the homepage you'll see the field

Obviously the image will display when viewed in portait mode(ipad portrait, iphone portrait).
