### ISSUE TITLE
Text overlaps the logo 

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#27]
See examples - can we fix this Mark?
<img width="605" alt="Screen Shot 2020-01-18 at 12 25 42 pm" src="https://user-images.githubusercontent.com/55725505/72852123-c655e100-3d01-11ea-99fa-a65233f5594f.png">
<img width="438" alt="Screen Shot 2020-01-18 at 12 36 35 pm" src="https://user-images.githubusercontent.com/55725505/72852124-c6ee7780-3d01-11ea-8845-bd318dd22908.png">

**Comment by markendley** [comment]
I just put a white transluecent background on the header

**Comment by LaraStudioFriday** [comment]
It seems a bit slow to kick in - see video i chatted to you

**Comment by markendley** [comment]
done

also changed it to pink (white wasn't working)

**Comment by LaraStudioFriday** [comment]
Ok, but still takes time to kick in - will send video

**Comment by markendley** [comment]
and you cleared cache?

**Comment by LaraStudioFriday** [comment]
Can we make this bar white again as you cant see the logo now

**Comment by markendley** [comment]
yes
