### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#28]
The  ‘hamburger’ menu moves to the left hand side for the room archive page, can we keep it on the right and the Instagram link on the left hand side.

**Comment by markendley** [comment]
$50 +GST

**Comment by LaraStudioFriday** [comment]
It should have always been on the right hand side - to keep it consistent.

**Comment by markendley** [comment]
when I did those pages I following Jake's design

Pretty sure I would kept them in the same spot otherwise

**Comment by LaraStudioFriday** [comment]
When jake designed it he didnt have a hamburger menu - see image. 

It was when we copied the flack style website that the hamburger came in. It should have always been in the same place for consistency. Thanks

<img width="1024" alt="Screen Shot 2020-01-28 at 10 39 54 am" src="https://user-images.githubusercontent.com/55725505/73223536-8c318700-41ba-11ea-947b-e4ec984f9cc6.png">

**Comment by markendley** [comment]
Yes, the client has pretty much taken over the design direction of this site.

Even for simple changes, she has to pay us for our time.

**Comment by markendley** [comment]
done, merry christmas

**Comment by LaraStudioFriday** [comment]
Cool - and can we please add the Instagram icon to left hand side?
