### ISSUE TITLE
underscore

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#31]
Can we delete the underscore to the text used in the project names and room names.

**Comment by markendley** [comment]
What underscore?

Is she talking about the urls?

**Comment by LaraStudioFriday** [comment]
The lines under these words...
<img width="248" alt="Screen Shot 2020-01-23 at 8 41 14 am" src="https://user-images.githubusercontent.com/55725505/72936872-30cb5780-3dbc-11ea-9fab-8784302cd8c8.png">
<img width="149" alt="Screen Shot 2020-01-23 at 8 41 29 am" src="https://user-images.githubusercontent.com/55725505/72936873-3163ee00-3dbc-11ea-8908-d26473faa777.png">

**Comment by markendley** [comment]
done
