### ISSUE TITLE
Rooms and project pages

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#32]
For the rooms and projects pages, can we invert where we use the pink. Ie iwhen you click on the rooms or project page, you will see all images in normal colour - like the attached image of Blushing Bulli and Living. Then when you hover over the image the pink overlay appears.
<img width="1267" alt="Screen Shot 2020-01-22 at 11 34 22 am" src="https://user-images.githubusercontent.com/55725505/72855972-56e5ee80-3d0d-11ea-8670-805108b99138.png">
<img width="1275" alt="Screen Shot 2020-01-22 at 11 34 37 am" src="https://user-images.githubusercontent.com/55725505/72855973-56e5ee80-3d0d-11ea-8c48-cde9f290642c.png">

**Comment by markendley** [comment]
done
