### ISSUE TITLE
WHO / WHAT IS / PROCESS / CONTACT 

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#33]
Client - "Feeling like too much pink in these sections. So can we keep the flash of pink before seeing the page but then loose the pink overlay. "

Mark can we add a white overlay to theses image, to white wash them and turn the text to pink.

**Comment by markendley** [comment]
Correct me if I'm wrong....
1. Page loads pink (like it does now)
2. After a split second the pink overlay goes away
3. Instead of pink overlay like we have now, we have a white overlay. And the text over this white over lay is... black? And a pink heading?

$100 +GST

**Comment by LaraStudioFriday** [comment]
Ok - will let the client know. All text turns to pink

**Comment by markendley** [comment]
Do I have the go ahead?

**Comment by LaraStudioFriday** [comment]
Yes you have the go ahead, thanks

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Can we make it much whiter to make the text stand out?

**Comment by markendley** [comment]
changed it from 50% to 80%
