### ISSUE TITLE
Rooms and project gallery pages

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#36]
Projects / Rooms - Can we also change the pink wash to a white wash on the project and room galleries
<img width="1268" alt="Screen Shot 2020-01-30 at 2 10 19 pm" src="https://user-images.githubusercontent.com/55725505/73416890-5b904f80-436a-11ea-938a-3f19752b5f26.png">
.

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
Can we reduce the amount of white wash on these - to see more of the image in the background?

**Comment by markendley** [comment]
before it was 80%
I changed it to 60%
