### ISSUE TITLE
Individual project

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#4]
Can we please crop the image, so an info button can sit underneath (just where the caption sits on the homepage) 
<img width="1272" alt="Screen Shot 2019-11-12 at 11 07 00 am" src="https://user-images.githubusercontent.com/55725505/68630885-d8b2e200-053c-11ea-8674-373cc68c4d50.png">
<img width="1267" alt="Screen Shot 2019-11-12 at 11 07 40 am" src="https://user-images.githubusercontent.com/55725505/68630888-dcdeff80-053c-11ea-80c0-eff263a8ce01.png">

On clicking the info button, the project description will appear above.

**Comment by markendley** [comment]
Afraid this will cost an extra $400 +GST.

(This is just like topology when we start complicating things with scroll events and fixed heights)
