### ISSUE TITLE
Slide 12

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#5]
Can we please put a slash in front of the 12, e.g /12, so a user knows that the image slides are 1, 2 3 etc of 12. 

<img width="1267" alt="Screen Shot 2019-11-12 at 11 11 46 am" src="https://user-images.githubusercontent.com/55725505/68631018-4232f080-053d-11ea-9ce4-ee003d28edd0.png">

**Comment by markendley** [comment]
done
