### ISSUE TITLE
Rooms Page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#7]
Same comments apply as comment 3 and 6

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
"I think I would like to give it a try though, for a bit of fun and interactively. The idea was the the icon in the house format would just appear on a page after clicking the ‘rooms’ tab. Once a room was selected they would need to appear again at the top of the page. Does that make sense? "
<img width="504" alt="Screen Shot 2019-12-04 at 11 22 12 am" src="https://user-images.githubusercontent.com/55725505/70101245-70ad7280-1688-11ea-8ebb-a233972f683a.png">

If you can put in a placeholder for the icon - Jake will add these after

**Comment by markendley** [comment]
duplicate
