### ISSUE TITLE
Rooms page question

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/hmm#8]
Are these images uploaded like a gallery - or are they tagged in some way?

Thanks, 
Lara

**Comment by markendley** [comment]
On this page
http://marke2.sg-host.com/hemma/room/

each 'room' is a a custom post type
you create each room just like creating a new post
and you'll assign them to categories

![Screen Shot 2019-11-16 at 6 41 58 pm](https://user-images.githubusercontent.com/6570606/68989890-d59f5500-08a0-11ea-837f-a7e534460f90.png)
